# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beeDLCZ4TBVgawaD7JGmFokaG-1FWogG
"""

# Install required packages
!pip install PyPDF2 langchain google-generativeai langchain-community

# Paste your Gemini API key here
import os
import google.generativeai as genai

GOOGLE_API_KEY = "AIzaSyC1XiI7BuiR9BBb4ApLogtzh2UjPRJIV60"  # <-- Replace with your key
genai.configure(api_key=GOOGLE_API_KEY)

import PyPDF2
from google.colab import files

# Upload your course document
uploaded = files.upload()

# Extract text
study_material = ""
for filename in uploaded:
    with open(filename, "rb") as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            study_material += page.extract_text()

print(study_material[:1000])  # Preview first 1000 characters

model = genai.GenerativeModel("gemini-2.0-flash")

def summarize_text(text):
    prompt = f"Summarize the following study material into key bullet points:\n\n{text}"
    response = model.generate_content(prompt)
    return response.text

summary = summarize_text(study_material)
print("🔹 Summary:\n", summary)

def generate_mcqs(summary):
    prompt = f"""Based on the following summary, generate 2 multiple-choice questions (MCQs).
Each question should have 4 options and clearly specify the correct answer at the end:

Summary:
{summary}
"""
    response = model.generate_content(prompt)
    return response.text

mcqs = generate_mcqs(summary)
print("📝 Quiz Questions:\n", mcqs)

from IPython.display import Markdown, display

def display_markdown(text):
    display(Markdown(text))

display_markdown(f"### 📚 **Study Summary**\n{summary}")
display_markdown(f"### ❓ **Quiz Questions**\n{mcqs}")

# Save summary and quiz to a text file
output_text = f"""📚 Summary:\n{summary}\n\n📝 Quiz Questions:\n{mcqs}"""

# Write to file
output_path = "/content/study_summary_and_quiz.txt"
with open(output_path, "w") as f:
    f.write(output_text)

# Download the file
from google.colab import files
files.download(output_path)